package org.climatemonitoring.clientCM.gui.views;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.climatemonitoring.shared.models.MonitoringCenter;
import org.climatemonitoring.shared.models.User;
import org.climatemonitoring.clientCM.gui.controllers.CenterSelectionGUIController;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.ArrayList;
import java.util.Locale;

public class CenterSelectionGUI extends JFrame {
    private JPanel centerRegistrationPanel;
    private JLabel climatemonitoringLabel;
    private JLabel centerRegistrationLabel;
    private JLabel centerRegistrationLabel2;
    private JButton completeRegistrationButton;
    private JLabel centerRegisrationLabel3;
    private JTable centersTable;
    private JPanel centersSelectionPanel;
    private JButton centerRegistrationButton;
    private JButton backButton;
    private JScrollPane centersScroll;

    public CenterSelectionGUI(User user, ArrayList<MonitoringCenter> centersList) {
        setTitle("Climate Monitoring");
        setContentPane(centerRegistrationPanel);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1920, 1024);// To set fixed dimensions
        new CenterSelectionGUIController(this, user, centersList);
    }

    public JPanel getCenterRegistrationPanel() {
        return centerRegistrationPanel;
    }

    public void setCenterRegistrationPanel(JPanel centerRegistrationPanel) {
        this.centerRegistrationPanel = centerRegistrationPanel;
    }

    public JLabel getClimatemonitoringLabel() {
        return climatemonitoringLabel;
    }

    public void setClimatemonitoringLabel(JLabel climatemonitoringLabel) {
        this.climatemonitoringLabel = climatemonitoringLabel;
    }

    public JLabel getCenterRegistrationLabel() {
        return centerRegistrationLabel;
    }

    public void setCenterRegistrationLabel(JLabel centerRegistrationLabel) {
        this.centerRegistrationLabel = centerRegistrationLabel;
    }

    public JLabel getCenterRegistrationLabel2() {
        return centerRegistrationLabel2;
    }

    public void setCenterRegistrationLabel2(JLabel centerRegistrationLabel2) {
        this.centerRegistrationLabel2 = centerRegistrationLabel2;
    }

    public JButton getCompleteRegistrationButton() {
        return completeRegistrationButton;
    }

    public void setCompleteRegistrationButton(JButton completeRegistrationButton) {
        this.completeRegistrationButton = completeRegistrationButton;
    }

    public JLabel getCenterRegisrationLabel3() {
        return centerRegisrationLabel3;
    }

    public void setCenterRegisrationLabel3(JLabel centerRegisrationLabel3) {
        this.centerRegisrationLabel3 = centerRegisrationLabel3;
    }

    public JTable getCentersTable() {
        return centersTable;
    }

    public void setCentersTable(JTable centersTable) {
        this.centersTable = centersTable;
    }

    public JPanel getCentersSelectionPanel() {
        return centersSelectionPanel;
    }

    public void setCentersSelectionPanel(JPanel centersSelectionPanel) {
        this.centersSelectionPanel = centersSelectionPanel;
    }

    public JButton getCenterRegistrationButton() {
        return centerRegistrationButton;
    }

    public void setCenterRegistrationButton(JButton centerRegistrationButton) {
        this.centerRegistrationButton = centerRegistrationButton;
    }

    public JButton getBackButton() {
        return backButton;
    }

    public void setBackButton(JButton backButton) {
        this.backButton = backButton;
    }

    public JScrollPane getCentersScroll() {
        return centersScroll;
    }

    public void setCentersScroll(JScrollPane centersScroll) {
        this.centersScroll = centersScroll;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        centerRegistrationPanel = new JPanel();
        centerRegistrationPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
        centerRegistrationPanel.setBackground(new Color(-9473675));
        centerRegistrationPanel.setForeground(new Color(-9473675));
        climatemonitoringLabel = new JLabel();
        climatemonitoringLabel.setBackground(new Color(-1));
        Font climatemonitoringLabelFont = this.$$$getFont$$$("JetBrains Mono ExtraBold", Font.BOLD, 72, climatemonitoringLabel.getFont());
        if (climatemonitoringLabelFont != null) climatemonitoringLabel.setFont(climatemonitoringLabelFont);
        climatemonitoringLabel.setForeground(new Color(-1));
        climatemonitoringLabel.setText("Climate Monitoring");
        centerRegistrationPanel.add(climatemonitoringLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        centersSelectionPanel = new JPanel();
        centersSelectionPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        centersSelectionPanel.setBackground(new Color(-9473675));
        centersSelectionPanel.setForeground(new Color(-9473675));
        centerRegistrationPanel.add(centersSelectionPanel, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        centersScroll = new JScrollPane();
        centersSelectionPanel.add(centersScroll, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        centersTable = new JTable();
        centersScroll.setViewportView(centersTable);
        centerRegistrationLabel = new JLabel();
        centerRegistrationLabel.setBackground(new Color(-1));
        Font centerRegistrationLabelFont = this.$$$getFont$$$(null, -1, 16, centerRegistrationLabel.getFont());
        if (centerRegistrationLabelFont != null) centerRegistrationLabel.setFont(centerRegistrationLabelFont);
        centerRegistrationLabel.setForeground(new Color(-1));
        centerRegistrationLabel.setText("Per completare la registrazione è necessario indicare il Centro di Monitaraggio di afferenza : ");
        centerRegistrationPanel.add(centerRegistrationLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        centerRegistrationLabel2 = new JLabel();
        centerRegistrationLabel2.setBackground(new Color(-1));
        Font centerRegistrationLabel2Font = this.$$$getFont$$$(null, -1, 16, centerRegistrationLabel2.getFont());
        if (centerRegistrationLabel2Font != null) centerRegistrationLabel2.setFont(centerRegistrationLabel2Font);
        centerRegistrationLabel2.setForeground(new Color(-1));
        centerRegistrationLabel2.setText(" - Se il Centro di Monitoraggio di tua afferenza è nella lista sottostante selezionalo e clicca su \"Completa Registrazione\"");
        centerRegistrationPanel.add(centerRegistrationLabel2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        completeRegistrationButton = new JButton();
        completeRegistrationButton.setBackground(new Color(-13947600));
        completeRegistrationButton.setForeground(new Color(-1));
        completeRegistrationButton.setText("Completa Registrazione");
        centerRegistrationPanel.add(completeRegistrationButton, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        centerRegisrationLabel3 = new JLabel();
        centerRegisrationLabel3.setBackground(new Color(-1));
        Font centerRegisrationLabel3Font = this.$$$getFont$$$(null, -1, 16, centerRegisrationLabel3.getFont());
        if (centerRegisrationLabel3Font != null) centerRegisrationLabel3.setFont(centerRegisrationLabel3Font);
        centerRegisrationLabel3.setForeground(new Color(-1));
        centerRegisrationLabel3.setText(" - Se il tuo centro di afferenza non è già registrato clicca su \"Registra Centro\" per procedere con la registrazione del centro");
        centerRegistrationPanel.add(centerRegisrationLabel3, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        centerRegistrationButton = new JButton();
        centerRegistrationButton.setBackground(new Color(-13947600));
        centerRegistrationButton.setForeground(new Color(-1));
        centerRegistrationButton.setText("Registra Centro");
        centerRegistrationPanel.add(centerRegistrationButton, new com.intellij.uiDesigner.core.GridConstraints(5, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setBackground(new Color(-13947600));
        backButton.setForeground(new Color(-1));
        backButton.setText("Indietro");
        centerRegistrationPanel.add(backButton, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return centerRegistrationPanel;
    }

}
